## ATIVIDADE 02


**○ Tipo:** Somativa;

**○ Tema:** Algoritmos básicos de programação em linguagem python e
análise de dados.

**○ Conteúdo:** Módulo 1 e 2.

**○ Participantes:** Individual.

**○ Avaliação do aluno.**

        ■ Objetivo: Avaliar desempenho do aluno sobre conhecimentos
        básicos de programação em linguagem python e visualização e
        análise de dados.

        ■ Nota: 0 a 3 supercrítico, 4 a 6 crítico, 5 a 7 razoável e 8 a 10
        bom;

        ■ Critérios avaliados: Respostas com coerência, coesão e com
        exemplos.
        
○ Informações adicionais: A atividade é composta por 5 questões
dissertativas sobre python e 5 questões sobre visualização e análise de
dados.

1. Escreva uma função que receba uma lista de números e retorne outra lista
com os números ímpares.

In [ ]:
#função
def filtrarImpares(list):
  impares = []

  for num in list:
    if num % 2 != 0:
      impares.append(num)

  return impares

In [ ]:
#exemplo de uso

list = [1, 2, 3, 4, 5, 6, 7, 8, 9]

print(filtrarImpares(list))

[1, 3, 5, 7, 9]

2. Escreva uma função que receba uma lista de números e retorne outra lista
com os números primos presentes.

In [ ]:
#função para verificar se o número é primo
def eh_primo(num):
  if num <= 1:
    return False

  for div in range(2, num):
      if num % div == 0:
        return False

  return True


#função para adicionar número primo a lista
def filtrarPrimos(list):
  primos = []

  for num in list:
    if eh_primo(num):
      primos.append(num)

  return primos

In [ ]:
#exemplo de uso

list = [1, 2, 3, 4, 5, 6, 7, 8, 9]

primos = filtrarPrimos(list)

print(primos)

[2, 3, 5, 7]

3. Escreva uma função que receba duas listas e retorne outra lista com os elementos que estão presentes em apenas uma das listas.

In [ ]:
#função para verificar números únicos nas listas

def elementosUnicos(list1, list2):
  elementos = []

  for num in list1:
    if num not in list2:
      elementos.append(num)

  for num in list2:
    if num not in list1:
      elementos.append(num)

  return elementos

In [ ]:
#Exemplo de uso

listA = [1, 2, 3, 5, 6, 8, 9]
listB = [0, 2, 3, 5, 6, 7, 8, 9]

unicos = elementosUnicos(listA, listB)
print(unicos)

[1, 0, 7]

4. Dada uma lista de números inteiros, escreva uma função para encontrar o segundo maior valor na lista.

In [ ]:
def segundoMaiorValor(list):
  maior = list[0]
  segundoMaior = list[0]

  for num in list:
    if num > maior:
      maior = num

    if num < maior and num > segundoMaior:
      segundoMaior = num

  return segundoMaior

In [ ]:
#exemplo de uso

list = [20, 60, 4, 23, 1]

print(f'o SEGUNDO MAIOR VALOR DA LISTA É {segundoMaiorValor(list)}')

o SEGUNDO MAIOR VALOR DA LISTA É 23

5. Crie uma função que receba uma lista de tuplas, cada uma contendo o
nome e a idade de uma pessoa, e retorne a lista ordenada pelo nome das
pessoas em ordem alfabética.

In [ ]:
def listaOrdenadaNome(list):
  inOrder = sorted(list, key = lambda nome: nome[0])
  return inOrder

In [ ]:
#exemplo de uso

list = [
    ("Diego", 23),
    ("Bruno", 15),
    ("Aline", 65)
]

print(listaOrdenadaNome(list))

[('Aline', 65), ('Bruno', 15), ('Diego', 23)]

6. Como identificar e tratar outliers em uma coluna numérica usando desvio
padrão ou quartis?

In [4]:
#USANDO DESVIO PADRÃO PARA IDENTIFICAR OUTLIER

#1 - Calcular média
#2 - Calcular desvio padrão
#3 - Definir limite inferior e superior

#EXEMPLO

import pandas as pd

df = pd.DataFrame({
    'idade': [22, 25, 27, 29, 30, 31, 32, 33, 35, 36, 38, 40, 42, 120]
})

print(df)

#Calculo media e desvio
media = df['idade'].mean()
desvio = df['idade'].std()

#fórmula para definir limites
limite_inferior = media - 3 * desvio
limite_superior = media + 3 * desvio

outliers_dp = df[(df['idade'] < limite_inferior) | (df['idade'] > limite_superior)]
print("OUTLIER IDENTIFICADO:")
print(outliers_dp)

    idade
0      22
1      25
2      27
3      29
4      30
5      31
6      32
7      33
8      35
9      36
10     38
11     40
12     42
13    120
OUTLIER IDENTIFICADO:
    idade
13    120

In [5]:
#USANDO DESVIO PADRÃO PARA IDENTIFICAR OUTLIER

#Quaris dividem os dados em 4 partes
#Q1 - 25%
#Q3 - 75%
#IQR = Q3 - Q1

#EXEMPLO

Q1 = df['idade'].quantile(0.25)
Q3 = df['idade'].quantile(0.75)
IQR = Q3 - Q1

lim_inf = Q1 - 1.5 * IQR
lim_sup = Q3 + 1.5 * IQR

outliers_iqr = df[(df['idade'] < lim_inf) | (df['idade'] > lim_sup)]
print(outliers_iqr)

    idade
13    120

É possível tratar Outliers Removendo-os, substituino pela média ou mediana ou mante-los caso sejam valores válidos

7. Como concatenar vários DataFrames (empilhando linhas ou colunas),
mesmo que tenham colunas diferentes?
Dica: Utiliza-se pd.concat() especificando axis=0 (linhas) ou axis=1
(colunas). Quando há colunas diferentes, os valores ausentes são
preenchidos com NaN.

In [10]:
df1 = pd.DataFrame([1, 2, 3, 4, 5],
                  [10, 20, 30, 40, 50])

df2 = pd.DataFrame([6, 7, 8, 9, 10],
                   [60, 70, 80, 90, 100])

#Empilhar linhas (axis = 0)
pd.concat([df1, df2], axis=0)

      0
10    1
20    2
30    3
40    4
50    5
60    6
70    7
80    8
90    9
100  10

In [11]:
#Empilhar colunas (axis = 1)
pd.concat([df1, df2], axis=1)

       0     0
10   1.0   NaN
20   2.0   NaN
30   3.0   NaN
40   4.0   NaN
50   5.0   NaN
60   NaN   6.0
70   NaN   7.0
80   NaN   8.0
90   NaN   9.0
100  NaN  10.0

8. Utilizando pandas, como realizar a leitura de um arquivo CSV em um
DataFrame e exibir as primeiras linhas?

In [ ]:
#ler arquivo
df = pd.read_csv('arquivo.csv')

#visualizar as primeiras linhas
df.head()

9. Utilizando pandas, como selecionar uma coluna específica e filtrar linhas
em um “DataFrame” com base em uma condição?

In [12]:
import pandas as pd

#EXEMPLO
df = pd.DataFrame({
    'nome': ['Ana', 'Bruno', 'Carlos', 'Daniela', 'Eduardo', 'Fernanda', 'Gabriel'],
    'idade': [23, 35, 28, 42, 31, 26, 39],
    'salario': [2500, 4500, 3200, 6000, 3800, 2900, 5200],
    'departamento': ['TI', 'RH', 'Financeiro', 'TI', 'Marketing', 'RH', 'TI']
})

print(df)

#Selecionar uma coluna
df['idade']

       nome  idade  salario departamento
0       Ana     23     2500           TI
1     Bruno     35     4500           RH
2    Carlos     28     3200   Financeiro
3   Daniela     42     6000           TI
4   Eduardo     31     3800    Marketing
5  Fernanda     26     2900           RH
6   Gabriel     39     5200           TI

0    23
1    35
2    28
3    42
4    31
5    26
6    39
Name: idade, dtype: int64

In [13]:
#filtrar linhas com condição
df[df['idade'] > 30]

      nome  idade  salario departamento
1    Bruno     35     4500           RH
3  Daniela     42     6000           TI
4  Eduardo     31     3800    Marketing
6  Gabriel     39     5200           TI

In [14]:
#Combinar condições
df[(df['idade'] > 30) & (df['salario'] > 3000)]

      nome  idade  salario departamento
1    Bruno     35     4500           RH
3  Daniela     42     6000           TI
4  Eduardo     31     3800    Marketing
6  Gabriel     39     5200           TI

10. Utilizando pandas, como lidar com valores ausentes (NaN) em um
DataFrame?

In [ ]:
#identificar NaN
df.isnull().sum

#remover linhas com NaN
df.dropna()

#Preencher valores
#com média
df['coluna'].fillna(df['coluna'].mean())

#com valor fixo
df['coluna'].fillna(0)

#substituir no prórprio DataFrame
df['coluna'].fillna(valor, inplace=True)